/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TelegramRouteImport } from './routes/telegram'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as Personal_landingRouteImport } from './routes/personal_landing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParcheCrearRouteImport } from './routes/parche.crear'
import { Route as ParcheCodeRouteImport } from './routes/parche.$code'
import { Route as ParcheCodeQuizRouteImport } from './routes/parche_.$code.quiz'
import { Route as ParcheCodeMatchRouteImport } from './routes/parche_.$code.match'

const TelegramRoute = TelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const Personal_landingRoute = Personal_landingRouteImport.update({
  id: '/personal_landing',
  path: '/personal_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcheCrearRoute = ParcheCrearRouteImport.update({
  id: '/parche/crear',
  path: '/parche/crear',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcheCodeRoute = ParcheCodeRouteImport.update({
  id: '/parche/$code',
  path: '/parche/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcheCodeQuizRoute = ParcheCodeQuizRouteImport.update({
  id: '/parche_/$code/quiz',
  path: '/parche/$code/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcheCodeMatchRoute = ParcheCodeMatchRouteImport.update({
  id: '/parche_/$code/match',
  path: '/parche/$code/match',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/personal_landing': typeof Personal_landingRoute
  '/registro': typeof RegistroRoute
  '/telegram': typeof TelegramRoute
  '/parche/$code': typeof ParcheCodeRoute
  '/parche/crear': typeof ParcheCrearRoute
  '/parche/$code/match': typeof ParcheCodeMatchRoute
  '/parche/$code/quiz': typeof ParcheCodeQuizRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/personal_landing': typeof Personal_landingRoute
  '/registro': typeof RegistroRoute
  '/telegram': typeof TelegramRoute
  '/parche/$code': typeof ParcheCodeRoute
  '/parche/crear': typeof ParcheCrearRoute
  '/parche/$code/match': typeof ParcheCodeMatchRoute
  '/parche/$code/quiz': typeof ParcheCodeQuizRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/personal_landing': typeof Personal_landingRoute
  '/registro': typeof RegistroRoute
  '/telegram': typeof TelegramRoute
  '/parche/$code': typeof ParcheCodeRoute
  '/parche/crear': typeof ParcheCrearRoute
  '/parche_/$code/match': typeof ParcheCodeMatchRoute
  '/parche_/$code/quiz': typeof ParcheCodeQuizRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/personal_landing'
    | '/registro'
    | '/telegram'
    | '/parche/$code'
    | '/parche/crear'
    | '/parche/$code/match'
    | '/parche/$code/quiz'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/personal_landing'
    | '/registro'
    | '/telegram'
    | '/parche/$code'
    | '/parche/crear'
    | '/parche/$code/match'
    | '/parche/$code/quiz'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/personal_landing'
    | '/registro'
    | '/telegram'
    | '/parche/$code'
    | '/parche/crear'
    | '/parche_/$code/match'
    | '/parche_/$code/quiz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  Personal_landingRoute: typeof Personal_landingRoute
  RegistroRoute: typeof RegistroRoute
  TelegramRoute: typeof TelegramRoute
  ParcheCodeRoute: typeof ParcheCodeRoute
  ParcheCrearRoute: typeof ParcheCrearRoute
  ParcheCodeMatchRoute: typeof ParcheCodeMatchRoute
  ParcheCodeQuizRoute: typeof ParcheCodeQuizRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/telegram': {
      id: '/telegram'
      path: '/telegram'
      fullPath: '/telegram'
      preLoaderRoute: typeof TelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal_landing': {
      id: '/personal_landing'
      path: '/personal_landing'
      fullPath: '/personal_landing'
      preLoaderRoute: typeof Personal_landingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parche/crear': {
      id: '/parche/crear'
      path: '/parche/crear'
      fullPath: '/parche/crear'
      preLoaderRoute: typeof ParcheCrearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parche/$code': {
      id: '/parche/$code'
      path: '/parche/$code'
      fullPath: '/parche/$code'
      preLoaderRoute: typeof ParcheCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parche_/$code/quiz': {
      id: '/parche_/$code/quiz'
      path: '/parche/$code/quiz'
      fullPath: '/parche/$code/quiz'
      preLoaderRoute: typeof ParcheCodeQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parche_/$code/match': {
      id: '/parche_/$code/match'
      path: '/parche/$code/match'
      fullPath: '/parche/$code/match'
      preLoaderRoute: typeof ParcheCodeMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  Personal_landingRoute: Personal_landingRoute,
  RegistroRoute: RegistroRoute,
  TelegramRoute: TelegramRoute,
  ParcheCodeRoute: ParcheCodeRoute,
  ParcheCrearRoute: ParcheCrearRoute,
  ParcheCodeMatchRoute: ParcheCodeMatchRoute,
  ParcheCodeQuizRoute: ParcheCodeQuizRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
